language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install: "sudo python setup.py install"
# command to run tests
script: "sudo python setup.py test" 
